spring:
  application:
    name: movie-catalog-service
  config:
    import: "optional:configserver:http://localhost:8888" # config-server micro runs 8888 in our project
#config-server i used so that's why no need to mention properties here ,mention in outside(check config server micro service you can understand)
#  datasource:
#    url: jdbc:mysql://localhost:3306/angular
#    username: root
#    password: root
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#server:
#  port: 8091
#
#eureka:
#  client:
#    server-url:
#      defaultZone: http://localhost:8761/eureka
