spring:
  application:
    name: doctor-consultation-service
  datasource:
     url: jdbc:mysql://localhost:3306/angular
     username: root
     password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8098
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka