server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          #search-locations: file:///C:/config
           search-locations: file:///C:\Users\Sreenivas Bandaru\Documents\Microservices\MicroService\moviestreaming-project\config
#the above search location means in that file configurations are availble
