spring:
  application:
    name: patient-registration-service
  datasource:
     url: jdbc:mysql://localhost:3306/angular
     username: root
     password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  
server:
  port: 8097
